version: "3.9"
name: media-suite
services:
  vpn:
    container_name: vpn
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - VPN_TYPE=openvpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
    volumes:
      - ${OVPN_PATH}:/gluetun/custom.conf:ro
    networks:
      - netwarrk
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
      - 9696:9696
      - 7777:7777
    restart: unless-stopped

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    depends_on:  
      vpn:
        condition: service_healthy
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=5080
    volumes:
      - qbittorrent-config:/config
      - ${MEDIA_MNT}/downloads:/downloads
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    depends_on:  
      vpn:
        condition: service_healthy
    network_mode: service:vpn
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - sabnzbd-config:/config
      - ${MEDIA_MNT}/downloads:/downloads
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    networks:
      netwarrk:
        ipv4_address: ${RADARR_STATIC_CONTAINER_IP}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - ${MEDIA_MNT}/downloads:/downloads
      - ${MEDIA_MNT}/movies:/movies
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      netwarrk:
        ipv4_address: ${SONARR_STATIC_CONTAINER_IP}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - sonarr-config:/config
      - ${MEDIA_MNT}/downloads:/downloads
      - ${MEDIA_MNT}/TV:/TV
    ports:
      - 8989:8989
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    networks:
      netwarrk:
        ipv4_address: ${READARR_STATIC_CONTAINER_IP}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - readarr-config:/config
      - ${MEDIA_MNT}/books:/books
      - ${MEDIA_MNT}/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    networks:
      netwarrk:
        ipv4_address: ${LIDARR_STATIC_CONTAINER_IP}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - lidarr-config:/config
      - ${MEDIA_MNT}/music:/music
      - ${MEDIA_MNT}/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped


  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    depends_on:
      vpn:
        condition: service_healthy
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - prowlarr-config:/config
    restart: unless-stopped

  recommendarr:
    container_name: recommendarr
    image: tannermiddleton/recommendarr:latest
    networks:
      - netwarrk
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      - PORT=3000
      - PUBLIC_URL=${RECOMMENDARR_URL}
    volumes:
      - recommendarr-data:/app/server/data
    ports:
      - 443:3000
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    networks:
      - netwarrk
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - jellyseerr-config:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

volumes:
  radarr-config:
  sonarr-config:
  readarr-config:
  lidarr-config:
  prowlarr-config:
  qbittorrent-config:
  sabnzbd-config:
  jellyseerr-config:
  recommendarr-data:

networks:
  netwarrk:
    external: true