version: "3.9"
name: media-suite
services:
  vpn:
    container_name: vpn
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - VPN_TYPE=openvpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
    volumes:
      - ${OVPN_PATH}:/gluetun/custom.conf:ro
    networks:
      - netwarrk
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
      - 9696:9696
      - 7777:7777
    restart: unless-stopped

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    depends_on:  
      vpn:
        condition: service_healthy
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=5080
    volumes:
      - qbittorrent-config:/config
      - ${MEDIA_MNT}/downloads:/downloads
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    depends_on:  
      vpn:
        condition: service_healthy
    network_mode: service:vpn
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - sabnzbd-config:/config
      - ${MEDIA_MNT}/downloads:/downloads
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    networks:
      netwarrk:
        ipv4_address: ${RADARR_STATIC_CONTAINER_IP}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - ${MEDIA_MNT}/downloads:/downloads
      - ${MEDIA_MNT}/movies:/movies
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      netwarrk:
        ipv4_address: ${SONARR_STATIC_CONTAINER_IP}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - sonarr-config:/config
      - ${MEDIA_MNT}/downloads:/downloads
      - ${MEDIA_MNT}/TV:/TV
    ports:
      - 8989:8989
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    networks:
      netwarrk:
        ipv4_address: ${READARR_STATIC_CONTAINER_IP}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - readarr-config:/config
      - ${MEDIA_MNT}/books:/books
      - ${MEDIA_MNT}/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    networks:
      netwarrk:
        ipv4_address: ${LIDARR_STATIC_CONTAINER_IP}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - lidarr-config:/config
      - ${MEDIA_MNT}/music:/music
      - ${MEDIA_MNT}/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped


  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    depends_on:
      vpn:
        condition: service_healthy
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - prowlarr-config:/config
    restart: unless-stopped

  recommendarr:
    container_name: recommendarr
    image: tannermiddleton/recommendarr:latest
    networks:
      - netwarrk
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      - PORT=3000
      - PUBLIC_URL=${RECOMMENDARR_URL}
    volumes:
      - recommendarr-data:/app/server/data
    ports:
      - 443:3000
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    networks:
      - netwarrk
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - jellyseerr-config:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

  cleanuperr:
    image: ghcr.io/flmorg/cleanuperr:latest
    container_name: cleanuperr
    networks:
      - netwarrk
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - LOGGING__FILE__PATH=/var/logs/
      - QUEUECLEANER__IGNORED_DOWNLOADS_PATH=/ignored.txt
      - QUEUECLEANER__IMPORT_FAILED_MAX_STRIKES=5
      - QUEUECLEANER__IMPORT_FAILED_IGNORE_PATTERNS__0=title mismatch
      - QUEUECLEANER__IMPORT_FAILED_IGNORE_PATTERNS__1=manual import required
      - QUEUECLEANER__STALLED_MAX_STRIKES=5
      - QUEUECLEANER__SLOW_MAX_STRIKES=5
      - QUEUECLEANER__SLOW_RESET_STRIKES_ON_PROGRESS=true
      - QUEUECLEANER__SLOW_MIN_SPEED=1MB
      - QUEUECLEANER__SLOW_MAX_TIME=20
      - QUEUECLEANER__SLOW_IGNORE_ABOVE_SIZE=60GB
      - CONTENTBLOCKER__ENABLED=true
      - CONTENTBLOCKER__IGNORED_DOWNLOADS_PATH=/ignored.txt
      - DOWNLOADCLEANER__ENABLED=true
      - DOWNLOADCLEANER__IGNORED_DOWNLOADS_PATH=/ignored.txt
      - DOWNLOADCLEANER__CATEGORIES__0__NAME=tv-sonarr
      - DOWNLOADCLEANER__CATEGORIES__0__MAX_RATIO=-1
      - DOWNLOADCLEANER__CATEGORIES__0__MIN_SEED_TIME=0
      - DOWNLOADCLEANER__CATEGORIES__0__MAX_SEED_TIME=240
      - DOWNLOADCLEANER__CATEGORIES__1__NAME=radarr
      - DOWNLOADCLEANER__CATEGORIES__1__MAX_RATIO=-1
      - DOWNLOADCLEANER__CATEGORIES__1__MIN_SEED_TIME=0
      - DOWNLOADCLEANER__CATEGORIES__1__MAX_SEED_TIME=240
      - DOWNLOAD_CLIENT=qBittorrent
      - QBITTORRENT__URL=${QBTT_URL}
      - QBITTORRENT__USERNAME=${QBTT_USER}
      - QBITTORRENT__PASSWORD=${QBTT_PASSWORD}
      - SONARR__ENABLED=true
      - SONARR__SEARCHTYPE=Episode
      - SONARR__BLOCK__PATH=${BLACKLIST}
      - SONARR__INSTANCES__0__URL=http://${SONARR_STATIC_CONTAINER_IP}:8989
      - SONARR__INSTANCES__0__APIKEY=${SONARR_API}
      - RADARR__ENABLED=true
      - RADARR__BLOCK__PATH=${BLACKLIST}
      - RADARR__INSTANCES__0__URL=http://${RADARR_STATIC_CONTAINER_IP}:7878
      - RADARR__INSTANCES__0__APIKEY=${RADARR_API}
      - LIDARR__ENABLED=true
      - LIDARR__BLOCK__PATH=${BLACKLIST}
      - LIDARR__INSTANCES__0__URL=http://${LIDARR_STATIC_CONTAINER_IP}:8686
      - LIDARR__INSTANCES__0__APIKEY=${LIDARR_API}
    volumes:
      - cleanuperr-config:/var/logs
    restart: unless-stopped
    

volumes:
  radarr-config:
  sonarr-config:
  readarr-config:
  lidarr-config:
  prowlarr-config:
  qbittorrent-config:
  sabnzbd-config:
  jellyseerr-config:
  recommendarr-data:
  cleanuperr-config:

networks:
  netwarrk:
    external: true